#!/usr/bin/env python3

# Generated by ChatGPT at https://chat.openai.com/chat by asking the following:
'''
generate python3 code that creates a 512k file from an algorithmically generated seed
'''
# With the following script and explanation:
'''
import os
import random

# set seed for reproducibility
random.seed(42)

filename = "512KB_file.txt"
file_size = 512 * 1024  # 512 KB

# Generate random data
data = bytearray([random.randint(0, 255) for i in range(file_size)])

# Write data to file
with open(filename, 'wb') as f:
    f.write(data)

print(f"Successfully generated {os.path.getsize(filename)} bytes of data to file '{filename}'.")
'''
'''
This code sets the seed to 42, which will ensure that the same sequence of
random numbers is generated every time the code is run. The bytearray function
creates an array of file_size random bytes, which are then written to a file
named "512KB_file.txt". The code then prints a message indicating the file has
been successfully created.
'''
'''
Note that I've changed the seed to an argument and changed the filename to
reflect the new size of 10KB
'''

import os
import random
import sys
from all_the_ugly import get_generator_args

options = None
the_args = get_generator_args(options)

# set seed for reproducibility
the_seed = the_args['the_seed']
try:
    int(the_seed)
except TypeError:
    print("Nope, that's not a number")
    sys.exit(1)
except ValueError:
    print("Oops, that's not quite a number")
    sys.exit(1)

random.seed(the_seed)

filename = "10KB_file.txt"
file_size = 10 * 1024  # 10 KB

# Generate random data
data = bytearray([random.randint(0, 255) for i in range(file_size)])

# Write data to file
with open(filename, 'wb') as f:
    f.write(data)

file_size = os.path.getsize(filename)
print(f"Successfully generated {file_size} bytes of data to file '{filename}'.")

